apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcdproxy
  labels:
    app: mcdproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcdproxy
  template:
    metadata:
      labels:
        app: mcdproxy
    spec:
      containers:
        - name: mcdproxy
          image: desxiaofeng/mcdproxy
          workingDir: /data
          command: ["mcdproxy"]
          args: ["{}.sducraft.top:25565", "bc.{}.svc.cluster.local:25565"]
          tty: true
          stdin: true
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /home/mc/muti_server_group/xiaofeng/mcdproxy
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mcdproxy
spec:
  selector:
    app: mcdproxy
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30000
  type: NodePort

